---
Initial Setup: Yes #yes/no

Number of Entities: 3

#List of entities denoted Entity #:
Entity 1 ID: JPMorgan
Entity 2 ID: Goldman Sachs
Entity 3 ID: Bloomberg
Entity 4 ID: Bombora

#List of requests denoted Request# etc.

Request 1 DocType: SSA18E Soc 2
Request 1 DocLoc: /home/polymathykhan/Downloads/Firefox Downloads/Fake Audits/SSA18ESoc2.pdf
Request 1 Orig: 1
Request 1 Vendor: 3
Request 1 Req: 2

Request 2 DocType: Third Party Risk Assessment Questionnaire
Request 2 DocLoc: /home/polymathykhan/Downloads/Firefox Downloads/Fake Audits/TPRAQ.pdf
Request 2 Orig: 2
Request 2 Vendor: 3
Request 2 Req: 1

Request 3 DocType: Big I New York Review
Request 3 DocLoc: /home/polymathykhan/Downloads/Firefox Downloads/Fake Audits/BigINewYorkReview.pdf
Request 3 Orig: 1
Request 3 Vendor: 4
Request 3 Req: 2